apiVersion: v1
kind: "Service"
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: htmldata
              subPath: h1
      volumes:
        - name: htmldata
          configMap:
            name: nginx-cm

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: default
data:
  h1: "this is h1"
  h2: "this is h2"
