global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus-state-metrics'
    static_configs:
      - targets: ['81.68.128.160:30034']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['81.68.128.160:9100','1.116.145.167:9100']

  - job_name: 'k8s-node'
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
        action: replace
    kubernetes_sd_configs:
      - api_server: https://1.116.145.159:6443/
        role: node
        bearer_token_file: /config/sa.token
        tls_config:
          insecure_skip_verify: true
  - job_name: 'k8s-kubelet'
    scheme: https
    bearer_token_file: /config/sa.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://1.116.145.159:6443/
        role: node
        bearer_token_file: /config/sa.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - target_label: __address__
        replacement: 1.116.145.159:6443
      - source_labels: [__meta_kubernetes_node_name]
        regex: '(.+)'
        replacement: '/api/v1/nodes/$1/proxy/metrics/cadvisor'
        target_label: __metrics_path__
        action: replace



