apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gin-test
  name: gin-test
  namespace: gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-test
  template:
    metadata:
      labels:
        app: gin-test
    spec:
      volumes:
        - name: config.conf-volume
          configMap:
            name: gin-test
      containers:
        - image: drzhangg/gin_demo1:v10
          name: gin-demo
          ports:
            - containerPort: 8181
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: config.conf-volume
              mountPath: /etc/config.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-test
  name: gin-svc
  namespace: gin
spec:
  ports:
    - port: 8181
      protocol: TCP
      targetPort: http
  selector:
    app: gin-test
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gin-test
  namespace: gin
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm

