apiVersion: v1
kind: "Service"
metadata:
  name: prometheus
  labels:
    name: prometheus
  namespace: prometheus
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.30.0
          name: prometheus
          command: ["/bin/sh","-ce","sleep 3600"]
          args:
            - "--web.enable-lifecycle"
            - "--config.file=/root/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: "/config/prometheus"
              name: prometheus-config
      volumes:
        - name: prometheus-config

